import Banner from "@/components/Banner";
import ProductCard from "@/components/cards/ProductCard";
import BreadCrumb from "@/components/layout/BreadCrumb";
import Head from "next/head";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAFP0lEQVR4AWJwL/AZUEy0wpfppiLPE80ArVdzfCRLEH7G2bYv1k425uJ8Fzv5xXg827Z9MZ9t27GNzepsz6va9OTX1zH++AY1NV1fVVd1VwcpQ7gLymDbvxuDZQplqNsVZXSgWv1mXL569boszeZtr2l27p7SqwRUYZwRGM1oDLS81+Buz9cvmveo3s3r1wa/wI15wbEeh/22eKzw3eezO2S/3y8rdgdod+9be+no8W1X07PkPSKgihT1A8PHlUHcw/r5VnyNvcO9GmfZiQ2yldIJ0gvbANmABxNl8bwAeEfUAeKDIlNDr/34y/w7xSVjukwAvJ6hDOZKFV7mfDVnxlebi/88bB/uCgOnAfIAZwCrADGANwCHAD8A7jGEst3i3vO5d+nykE4TUIVypmBc27DIjK+cpcdX6pskGLiecCNez2jPm/GSC4NBZylASUdlkjz+xGRZ/AsdElCFiyaAcWXDYjO+YvpMvmLa7HOTJOdFMEiXEmuC5Hx/EiU6Gl+Pl5zv0yaBSifRczDnfyq8LXTGy6fM/C5YvLQP/PRcd0sMjIYCHlAkPh7nevaZVglAiS2HhOOrjPXQ+NUyQ1MmebpNIpyJxDqWAGb8IAj9lXq5CV8xRef9UlqpF0jEUwTu0bnU7H1jIMdX6s1C49pSY/M+vUmAJKeWIpH2JIEQLr9hgZnO++9nirNAwbIdb14CzAdMaO07ki8zt5yPoB1pSub4xYhX7Zdu0+mYci/pMh/nvsbaQEcg0Hrlt2RB2dgGgUNNXsRX1/nZ0gmlS2QYOLvcQswj4PlvVgdk9uXmlsL3Axh+LyBAwj/j/gzJmW+pVS2oFQJp+H2SLP5GuaWNhBncQzBOkZjL6KRQ38Ix/Btw/knyFYKBMiZhnNshcK7UjOtHDf53KwR+FL6D7hB4v0Pkd+B9EBI4jrVPCHwHBq4CLgGyCQl812MJTJbH3yq3ssuCgUJQjtGgQlskTAXI8N2CEHyNIpaFsiYCXuYCgU/BwA2AAjAGUCfMNzyPaiUCGYKHeKcGDwH4UO9vE50idmqQwAEmAgoEMWaChEgk/iZLLEvgESCI8r622FT0AknIKiJDnRDKuBq/ow1MwjeoHCgFA78JBAiJuYAHwlIKyKQJkAHvUYPHUTkRR+SszgGiAwRCOWe6CvRcTybQBBBk221OTJYA7Rld+/iMMlqH5IRRMwFNnEUfWIbvCOvAci7qFE2ArX+qQnRJyBBYy/4Hso2MTjbK2ZXwfWElzJlmmIRNBzsQ7mIgf5cicAnrHvCIDFyFZSboM6VXS3QeANxYAjgNcmovuOpuu84M5SywqSCdUCbAA2W4a2KZ4bLK6jNTYYG6bfYD2AtQu+HGXtsJoXJIYlcS5OHmxBLAPlCEDSjpB259O1OsRyl2C2Tj+pLJnRg2AnRTsgUXJdIR/ck5HbTGtaCbxocBfmCMJ7XbE+LOBVOR1bCI9ISzDN+eITntg10M28+xYJIV/1EyxjNJe9d+V6x51eIFgUSlgRFfZSL60M7lwHxyDtgNsGxtIOxySIteyBh+gA5QvWC7BOhIbFB4iR7UWHF8tdiu+DMHLznp/2+RXbIM8Dc5J1yljVLb+ZcAo24ezcgZIYj7EU9Gtc6uj2pl87Lenx8hJyvjpwAt03DeIqR2u4WlWvfa4RQqxF4ZKE5TeDpfa3BfzDd4+5cqgkOPKSJjQ/+IXu32TvR2j++W7vJq3L4n4OL+Q3MvJyYbXfngo+d6jQCdH7pyDZWGKsP81zdGxe5Qvr50o3rlmmjNxs2O6q07+nW1Wv4HPXLt5tomshoAAAAASUVORK5CYII="
        />
      </Head>
      <main>
        <div>
          <Banner />
        </div>
        <div className="my-2  bg-light">
          <h4 className="text-center p-2 text-uppercase">Products</h4>
        </div>
        <div className="row">
          {products &&
            products.map((elements) => {
              return (
                <div key={elements.id} className="col-md-4">
                  <div className="mt-3">
                    <ProductCard product={elements} />
                  </div>
                </div>
              );
            })}
        </div>
      </main>
    </>
  );
}
export async function getServerSideProps(context) {
  let products = [];
  try {
    const response = await fetch("https://dummyjson.com/products");
    const result = await response.json();
    products = result.products;
  } catch (error) {
    return { notFound: true };
  }
  return {
    props: {
      products,
    },
  };
}
